### ISSUE TITLE
Clearly define Converter and provide list of converters

### ISSUE THREAD

**Issue by chinhuang007** [onnx/sigs#13]
What is a "Converter" in ONNX? We would like to have a clear definition to make sure the entire ONNX community uses the same interpretation. Then we will provide a complete list of ONNX converters. Later we will update the list with additional details.

**Comment by ebarsoum** [comment]
Hi @chinhuang007,

Converter in ONNX context, is converting from ML/DNN framework to ONNX, or vice versa.

**Comment by chinhuang007** [comment]
@ebarsoum Thanks for your suggestion. We were discussing it and chose to the broadest definition that includes backends like TensorRT, Habana, and Onnx Runtime. Are these ML/DNN framework? If most think not, we will certainly narrow down our definition.

**Comment by chinhuang007** [comment]
Close since we have reviewed the definition and list during the workshop. Let's continue to keep the list up-to-date.
