### ISSUE TITLE
Where/how to see current state (coverage, versioning, etc) for all converters

### ISSUE THREAD

**Issue by chinhuang007** [onnx/sigs#15]
ONNX users need to conveniently see the most recent state for all converters to ensure smooth conversion between frameworks/backends. We certainly don't intend to add much development work to individual converter communities. Therefore, we would like to investigate and propose some simple mechanism to make sure our end users have the best experience with ONNX converters as possible.

**Comment by winnietsang** [comment]
In order to display the "true" status of each converter, I vote for each converter to provide it's own status table. I've created a PR (https://github.com/onnx/onnx-tensorflow/pull/484) in onnx-tf converter to auto gen this table.

**Comment by chinhuang007** [comment]
A common landing page to view status for all converters will be available at converters/docs folder. It is up to each converter to provide updates to make it useful for onnx users.

**Comment by chinhuang007** [comment]
Close since the landing page is added, https://github.com/onnx/sigs/blob/master/converters/docs/ConvertersDashboard.md with a link to the auto-genarated report for ONNX-TF converter.
